### PR TITLE
Update init sequence for Windows types.

### PR DESCRIPTION
**Pull request by kinetiknz**
Introduce PlatformHandleType typedef in audioipc to match Gecko's
FileDescriptor.

Switch AudioIpcInitParams and audioipc_server_new_client file descriptor types
from int to PlatformHandleType to prep for Windows port changes.

### CODE REVIEW

**Comment by kinetiknz** [comment]
Many more patches coming as I finish splitting them up.

r? @ChunMinChang

**Comment by ChunMinChang** [comment]
Looking into it.

**Comment by ChunMinChang** [comment]
Looks good to me.
One question: Is it ok if we don't check the returned value from ```CloseHandle(...)```(```close(...)``` in unix) ?

**Comment by kinetiknz** [comment]
> Is it ok if we don't check the returned value from `CloseHandle(...)`(`close(...)` in unix) ?

It's a fairly common pattern (for better or worse) - often by the time you're closing the resource there's not much you can do if it fails.  There are definitely cases where that pattern can lead to data loss when dealing with file I/O, though, for example issue 32255 in Rust.

It wouldn't hurt to log if we get an error from close/CloseHandle though, so I can add that if you think it's worthwhile.

**Comment by ChunMinChang** [comment]
Per discussion on IRC, it's better to check the returned [```PlatformHandleType```][asnc] from ```audioipc_server_new_client```, in case it's a [invalid result][rust]. I think it's ok to leave ```Close``` and ```CloseHandle(...)``` as they are if we can make sure the returned values are valid.

[asnc]: https://searchfox.org/mozilla-central/rev/a0333927deabfe980094a14d0549b589f34cbe49/dom/media/CubebUtils.cpp#406 "audioipc_server_new_client"
[rust]: https://github.com/djg/audioipc-2/blob/d8972b14d3ba7ce42fdb696c433308f6ae4f2869/server/src/lib.rs#L520 "audioipc_server_new_client"

**Comment by kinetiknz** [comment]
Latest commit addresses your comment.  Thanks for pointing that out!

**Comment by ChunMinChang** [comment]
Looks good! Glad to help!

**Review by ChunMinChang — APPROVED** [review]

**Comment by kinetiknz** [comment]
Merged in https://github.com/kinetiknz/audioipc-2/commit/0f7dca5a501d0bf2292c899e94d631c9c3940560

**Pull request closed without merging**
